Serilog:
    Using: [Serilog.Sinks.Console]
    MinimumLevel: 
      Default: Debug
      Override:
        Microsoft: Information
    Enrich: [FromLogContext, WithMachineName, WithProcessId]

FileSettings:
  UploadFolderName: uploads
  AllowedExtensions:
    - .pdf
    - .jpg
    - .jpeg
    - .png

AllowedHosts: '*'
