<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Protos\File\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Api.Gax.Grpc" />
    <PackageReference Include="Grpc.Net.Common" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\File\FileService.proto" GrpcServices="Both" />
	</ItemGroup>
	


</Project>
