services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rbc_sqlserver
    env_file:
    - .env
    environment:
    - ACCEPT_EULA=${ACCEPT_EULA}
    - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    - MSSQL_PID=${MSSQL_PID}
    ports:
    - "1433:1433"
    volumes:
    - sqlserver_data:/var/opt/mssql
    networks:
    - rbc_network

  mssql-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: rbc_sqlserver_init
    depends_on:
      sqlserver:
        condition: service_started
    volumes:
    - ./schema.sql:/scripts/schema.sql
    - ./seed.sql:/scripts/seed.sql
    environment:
    - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    entrypoint: /bin/bash -c "
      echo 'Waiting for SQL Server...';
      for i in {1..50}; do
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q 'SELECT 1' > /dev/null 2>&1;
        if [ $$? -eq 0 ]; then
          echo 'SQL Server is UP. Running scripts...';
          /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -i /scripts/schema.sql && \
          /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -i /scripts/seed.sql;
          echo 'Init completed.';
          exit 0;
        fi;
        echo 'Still waiting...';
        sleep 2;
      done;
      echo 'Failed to connect to SQL Server'; exit 1;"
    networks:
      - rbc_network

  webapp:
    build:
      context: .
      dockerfile: src/RBC_consulting.Api/Dockerfile
    container_name: webapp
    env_file:
    - .env
    environment:
    - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    - ASPNETCORE_URLS=${ASPNETCORE_URLS}
    - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=${DB_NAME};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
    ports:
    - "5000:80"
    - "5001:443"
    depends_on: [sqlserver, mssql-init]
    networks:
    - rbc_network
    volumes:
    - webapp_uploads:/app/wwwroot/uploads

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus:/prometheus 
    depends_on: ["webapp"]
    ports:
    - "9090:9090"
    networks:
    - rbc_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
    - GF_SECURITY_ADMIN_USER=admin 
    - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
    - grafana:/var/lib/grafana 
    depends_on: ["prometheus", "loki"]
    ports:
    - "3000:3000"
    networks:
    - rbc_network
   
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
    - loki:/loki 
    - ./test/loki-config.yaml:/etc/loki/local-config.yaml 
    ports:
    - "3100:3100"
    networks:
    - rbc_network
  
  mssql-exporter:
    image: awaragi/prometheus-mssql-exporter
    container_name: mssql_exporter
    environment:
    - USERNAME=sa
    - PASSWORD=${MSSQL_SA_PASSWORD}
    depends_on: ["sqlserver"]
    ports:
    - "9182:9182"
    networks:
    - rbc_network
  

volumes:
  sqlserver_data:
  webapp_uploads:
  prometheus:
  grafana:
  loki:

networks:
  rbc_network:
    driver: bridge