services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rbc_sqlserver
    env_file:
    - .env
    environment:
    - ACCEPT_EULA=${ACCEPT_EULA}
    - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    - MSSQL_PID=${MSSQL_PID}
    ports:
    - "1433:1433"
    volumes:
    - sqlserver_data:/var/opt/mssql

  mssql-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: rbc_sqlserver_init
    depends_on:
      sqlserver:
        condition: service_started
    volumes:
    - ./configs/test/sql/schema.sql:/scripts/schema.sql
    - ./configs/test/sql/seed.sql:/scripts/seed.sql
    environment:
    - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    entrypoint: /bin/bash -c "
      echo 'Waiting for SQL Server...';
      for i in {1..50}; do
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q 'SELECT 1' > /dev/null 2>&1;
        if [ $$? -eq 0 ]; then
          echo 'SQL Server is UP. Running scripts...';
          /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -i /scripts/schema.sql && \
          /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -i /scripts/seed.sql;
          echo 'Init completed.';
          exit 0;
        fi;
        echo 'Still waiting...';
        sleep 2;
      done;
      echo 'Failed to connect to SQL Server'; exit 1;"

  webapp:
    build:
      context: .
      dockerfile: src/webapp/WebApp/Dockerfile
    container_name: webapp
    env_file:
    - .env
    environment:
    - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    - ASPNETCORE_URLS=${ASPNETCORE_URLS}
    - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=${DB_NAME};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
    ports:
    - "5000:80"
    depends_on: [sqlserver, mssql-init]
    volumes:
    - webapp_uploads:/app/wwwroot/uploads

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - ./configs/test/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus:/prometheus
    depends_on: ["webapp"]
    ports:
    - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
    - grafana:/var/lib/grafana
    - ./configs/test/grafana/provisioning:/etc/grafana/provisioning
    - ./configs/test/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on: ["prometheus", "loki"]
    ports:
    - "3000:3000"
   
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
    - loki:/loki 
    - ./configs/test/loki/loki-config.yml:/etc/loki/local-config.yaml 
    ports:
    - "3100:3100"
  
  mssql-exporter:
    image: awaragi/prometheus-mssql-exporter
    container_name: mssql_exporter
    environment:
    - SERVER=sqlserver
    - USERNAME=sa
    - PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
    - "4000:4000"
    depends_on: ["sqlserver"]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
    - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq


volumes:
  sqlserver_data:
  webapp_uploads:
  prometheus:
  grafana:
  loki:
  rabbitmq_data: