services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rbc_sqlserver
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - rbc_network

  mssql-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: rbc_sqlserver_init
    depends_on:
      sqlserver:
        condition: service_started
    volumes:
      - ./schema.sql:/scripts/schema.sql
      - ./seed.sql:/scripts/seed.sql
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    entrypoint: /bin/bash -c "
      echo 'Waiting for SQL Server...';
      for i in {1..50}; do
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q 'SELECT 1' > /dev/null 2>&1;
        if [ $$? -eq 0 ]; then
          echo 'SQL Server is UP. Running scripts...';
          /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -i /scripts/schema.sql && \
          /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -i /scripts/seed.sql;
          echo 'Init completed.';
          exit 0;
        fi;
        echo 'Still waiting...';
        sleep 2;
      done;
      echo 'Failed to connect to SQL Server'; exit 1;"
    networks:
      - rbc_network

  webapp:
    build:
      context: src
      dockerfile: RBC_consulting.Api/Dockerfile
    container_name: webapp
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=${DB_NAME};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - sqlserver
      - mssql-init
    networks:
      - rbc_network
    volumes:
      - webapp_uploads:/app/wwwroot/uploads


  

volumes:
  sqlserver_data:
  webapp_uploads:

networks:
  rbc_network:
    driver: bridge