using iTextSharp.text;
using iTextSharp.text.pdf;
using WebApp.Contracts.Pdf;
using PdfDocument = WebApp.Contracts.Pdf.PdfDocument;

namespace WebApp.Infrastructure.Pdf;

internal class PdfService : IPdfService
{
    private const string PdfContentType = "application/pdf";
    private const string DefaultFont = FontFactory.HELVETICA_BOLD;

    public Task<PdfDocument> GenerateEmployeesPdfAsync(IEnumerable<EmployeePdfRow> rows)
    {
        using var memoryStream = new MemoryStream();
        var document = new Document(PageSize.A4.Rotate(), 25, 25, 30, 30);
        var writer = PdfWriter.GetInstance(document, memoryStream);

        document.Open();

        var titleFont = FontFactory.GetFont(DefaultFont, 18);
        var headerFont = FontFactory.GetFont(DefaultFont, 10);
        var cellFont = FontFactory.GetFont(DefaultFont, 9);
        var footerFont = FontFactory.GetFont(FontFactory.HELVETICA_OBLIQUE, 8);

        document.Add(new Paragraph("Detailed Employee Report", titleFont)
        {
            Alignment = Element.ALIGN_CENTER,
            SpacingAfter = 10
        });

        document.Add(new Paragraph($"Export Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}", cellFont)
        {
            Alignment = Element.ALIGN_CENTER,
            SpacingAfter = 15
        });

        var table = new PdfPTable(8)
        {
            WidthPercentage = 100,
            SpacingBefore = 10,
            SpacingAfter = 10
        };

        table.SetWidths([8f, 17f, 13f, 13f, 11f, 17f, 13f, 11f]);

        AddHeaderCell(table, "ID", headerFont);
        AddHeaderCell(table, "Full Name", headerFont);
        AddHeaderCell(table, "Position", headerFont);
        AddHeaderCell(table, "Department", headerFont);
        AddHeaderCell(table, "Hire Date", headerFont);
        AddHeaderCell(table, "Email", headerFont);
        AddHeaderCell(table, "Phone", headerFont);
        AddHeaderCell(table, "Salary", headerFont);

        var rowList = rows.ToList();
        foreach (var row in rowList)
        {
            AddCell(table, row.Id.ToString(), cellFont);
            AddCell(table, row.FullName, cellFont);
            AddCell(table, row.Position, cellFont);
            AddCell(table, row.Department, cellFont);
            AddCell(table, row.HireDate.ToString("yyyy-MM-dd"), cellFont);
            AddCell(table, row.Email ?? "", cellFont);
            AddCell(table, row.Phone ?? "", cellFont);
            AddCell(table, row.Salary is null ? "$0.00" : row.Salary.Value.ToString("C"), cellFont);
        }

        document.Add(table);

        document.Add(new Paragraph(
            $"Total Employees: {rowList.Count} | Generated by RBC Consulting Employee Management System",
            footerFont)
        {
            Alignment = Element.ALIGN_CENTER,
            SpacingBefore = 20
        });

        document.Close();
        writer.Close();

        var fileName = $"Employees_{DateTime.Now:yyyyMMdd}.pdf";
        return Task.FromResult(new PdfDocument(memoryStream.ToArray(), PdfContentType, fileName));
    }

    private static void AddHeaderCell(PdfPTable table, string text, Font font)
    {
        var cell = new PdfPCell(new Phrase(text, font))
        {
            BackgroundColor = new BaseColor(230, 230, 230),
            HorizontalAlignment = Element.ALIGN_CENTER,
            VerticalAlignment = Element.ALIGN_MIDDLE,
            Padding = 5
        };
        table.AddCell(cell);
    }

    private static void AddCell(PdfPTable table, string text, Font font)
    {
        var cell = new PdfPCell(new Phrase(text, font))
        {
            HorizontalAlignment = Element.ALIGN_LEFT,
            VerticalAlignment = Element.ALIGN_MIDDLE,
            Padding = 5
        };
        table.AddCell(cell);
    }
}
