<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Settings\**" />
    <EmbeddedResource Remove="Settings\**" />
    <None Remove="Settings\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RBC_consulting.Contracts\RBC_consulting.Contracts.csproj" />
    <ProjectReference Include="..\RBC_consulting.Application\RBC_consulting.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="iTextSharp.LGPLv2.Core" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
